CREATE SEQUENCE "ICARGO"."STOCKXESTACION_SEQ" INCREMENT BY 1 
    START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE 
    CACHE 20 NOORDER;
/
create trigger "ICARGO"."STOCKXESTACION_TRIGGER" 
BEFORE INSERT ON "STOCKXESTACION" 
FOR EACH ROW
begin select STOCKXESTACION_SEQ.nextval into :new.STOEST_ID from dual;
end;
/

